upstream backend_nodes {
    server app_2:8000;
    server app_3:8000;
    server app_node:8000;
}

server {
    listen 80;

    # Главное окно (Лаба 1-2)
    location / {
        proxy_pass http://app_1:8000;
        proxy_set_header Host $host;
    }

    # Балансировщик (Лаба 3-4)
    location /api/status {
        proxy_pass http://backend_nodes/api/status;
        proxy_set_header Host $host;
    }
}